### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [pvdb/oh-my-zsh-custom#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by unixorn** [comment]
Also, please rename it to something less generic - custom is overused. Maybe pvdb-theme?

**Comment by pvdb** [comment]
Hey @unixorn - thanks for your interest in my plugin, but seeing as it has my personal ZSH functions/aliases/settings/... I very much doubt it is of much use to anyone else, hence why I haven't really tried to tidy it up and make it pristine, at least not yet... lemme consider it though, and rename it if I think it's worth sharing it with a wider audience.

**Comment by unixorn** [comment]
That's reasonable. If/when you decide to make it public, please open an issue or PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).

I look for new plugins and themes every day or so to keep the list up to date, that's how I spotted your repo.
